import json, subprocess, os
from pathlib import Path
from datetime import datetime
ROOT=Path('Module10_Dry_Run')
OUT=ROOT/'_module10_dryrun_outputs'
APP=ROOT/'standalone-course-mvp'
reports=OUT/'reports'
source=json.load(open(OUT/'source_map/source_objective_map.json',encoding='utf-8'))
content=json.load(open(OUT/'data/module10.content.json',encoding='utf-8'))
activities=json.load(open(OUT/'data/module10.activities.json',encoding='utf-8'))
img=json.load(open(OUT/'media/image_manifest.json',encoding='utf-8'))
sfx=json.load(open(OUT/'audio/sfx_manifest.json',encoding='utf-8'))
audio=json.load(open(OUT/'audio/audio_manifest.json',encoding='utf-8'))
objs=source['objectives']
checks=[]
def check(name, passed, evidence): checks.append((name, bool(passed), evidence))
check('16 objectives present', len(objs)==16, f"count={len(objs)}")
check('weighted minutes total exactly 180', sum(o['weighted_minutes'] for o in objs)==180, f"total={sum(o['weighted_minutes'] for o in objs)}")
check('each objective has >=3 activities', all(len(o['required_activities'])>=3 for o in objs), 'all source map objectives have 3 required activities')
check('activities JSON has 16 objectives', len(activities['objectives'])==16, f"count={len(activities['objectives'])}")
check('no clinical/certificate time in theory', all(o['excluded_certificate_minutes']==0 for o in objs), 'clinical deferred; certificate excluded')
check('source assets mapped', len(source['source_assets'])>=17, f"assets={len(source['source_assets'])}")
check('answer key internal-only', any(a['asset_id']=='sample_test_answer_key' and 'internal' in a['usage_boundary'] for a in source['source_assets']), 'sample_test_answer_key internal-only')
check('audio scripts/manifest queued no generation', audio['status']=='scripts_only_no_audio_generated', audio['status'])
check('SFX manifest license-gated', all('license' in i and i['license'] for i in sfx['items']), f"items={len(sfx['items'])}")
check('image prompts have alt text', all(i.get('alt_text') for i in img['items']), f"items={len(img['items'])}")
check('backup/ContentV2 not source authority', not source['validation']['backup_content_used_as_authority'] and not source['validation']['contentv2_used_as_authority'], 'false/false')
# Build already run; verify dist exists
check('app build artifact exists', (APP/'dist/index.html').exists(), 'dist/index.html present after npm run build')
files_created=[
 'Module10_Dry_Run/_module10_dryrun_outputs/source_map/source_objective_map.json','Module10_Dry_Run/_module10_dryrun_outputs/source_map/source_objective_map.md','Module10_Dry_Run/_module10_dryrun_outputs/data/module10.content.json','Module10_Dry_Run/_module10_dryrun_outputs/data/module10.activities.json','Module10_Dry_Run/_module10_dryrun_outputs/data/module10.schema.json','Module10_Dry_Run/_module10_dryrun_outputs/data/content.generated.json','Module10_Dry_Run/_module10_dryrun_outputs/audio/audio_manifest.json','Module10_Dry_Run/_module10_dryrun_outputs/audio/audio_scripts.csv','Module10_Dry_Run/_module10_dryrun_outputs/audio/sfx_manifest.json','Module10_Dry_Run/_module10_dryrun_outputs/media/image_manifest.json','Module10_Dry_Run/_module10_dryrun_outputs/media/image_prompt_queue.json','Module10_Dry_Run/_module10_dryrun_outputs/reports/time_allotment_report.md','Module10_Dry_Run/_module10_dryrun_outputs/reports/lessonplayer_review.md','Module10_Dry_Run/_module10_dryrun_outputs/reports/app_integration_notes.md','Module10_Dry_Run/standalone-course-mvp/src/data/module10.content.json','Module10_Dry_Run/standalone-course-mvp/src/data/module10.activities.json','Module10_Dry_Run/standalone-course-mvp/src/data/module10.schema.json','Module10_Dry_Run/standalone-course-mvp/src/data/module10.generated.ts','Module10_Dry_Run/standalone-course-mvp/src/data/module10.content.generated.json']
files_modified=['Module10_Dry_Run/standalone-course-mvp/src/data/contentV2.generated.ts','Module10_Dry_Run/standalone-course-mvp/src/data/remediationOverrides.ts']
validation_status='PASS' if all(p for _,p,_ in checks) else 'FAIL'
val=['# Validation Report — NATP Module 10 Dry Run','',f'Date: {datetime.now().isoformat(timespec="seconds")}',f'Validation result: **{validation_status}**','','## Checks','','| Check | Status | Evidence |','|---|---:|---|']
for name,p,e in checks: val.append(f'| {name} | {"PASS" if p else "FAIL"} | {e} |')
val += ['','## Build Result','','`npm install` completed with existing audit warnings: 5 vulnerabilities (4 moderate, 1 critical). `npm run build` passed (`tsc && vite build`), producing `dist/index.html` and bundled assets. Large chunk warning noted.','','## Compliance Flags','','- No CDPH/TPRU approval claim.','- No certificate-production readiness claim.','- No online clinical-hour credit claim.','- No online hands-on competency validation claim.','- No PHI examples or requests intentionally generated.','- Sample test answer key mapped as internal-only.','','## Residual Risks','','- Generated instructional copy is source-map-derived draft and needs SME/compliance review before production.','- Speech audio was not generated; scripts/manifests only.','- SFX assets are queued/license-gated; no usable SFX selected.','- Images are prompt queue only; no generated images.','- Repo has unrelated dirty state outside Module10_Dry_Run that predates/exists outside this run.']
(reports/'validation_report.md').write_text('\n'.join(val)+'\n',encoding='utf-8')
watch=['# Watchdog Report — Module 10 Dry Run','','Status: completed monitoring pass.','','## Monitored Rules','','- Repo path: approved repo remained `C:/AI/Git/CNA_Recertification_Theory_Clinical_Support`.','- Branch: `module-10-source-first-dry-run`.','- Write scope: generated artifacts are under `Module10_Dry_Run`.','- Active scope: Module 10 only.','- Source authority: approved Module 10 PDF only; backups ignored.','- Time total: 180 theory minutes.','- Prohibited claims: not detected in generated reports/manifests.','- PHI risk: generated examples are generic/de-identified; no PHI requested.','- Answer keys: sample test answer key internal-only; no learner-facing key report generated.','','## Worker Failures / Reassignment','','- Packaged `lms-orchestrator` failed before work due pi-subagents extension conflict. Parent orchestrator reassigned manually.','- `source-extraction` async runner disappeared after producing only `module10_source_layout.txt`; parent orchestrator completed source extraction in-scope rather than stopping whole run.','','## Paused Jobs','','None. Media generation was intentionally queued/gated, not paused as a blocker.']
(reports/'watchdog_report.md').write_text('\n'.join(watch)+'\n',encoding='utf-8')
outside=subprocess.getoutput("git status --short -- . ':(exclude)Module10_Dry_Run' | head -40")
fh=['# Final Handoff — NATP Module 10 Vital Signs Source-First Dry Run','',f'Date: {datetime.now().isoformat(timespec="seconds")}', '', '## Active Requirements Used','','Authorized full orchestration for NATP Module 10: Vital Signs only; 180 weighted theory minutes; source authority is the official Module 10 PDF; no old ContentV2/backups; no deployment/commit/push/PR; no approval, certificate, clinical-hour, or online competency claims.','','## Repo / Branch / Scope','','- Repo path: `C:/AI/Git/CNA_Recertification_Theory_Clinical_Support`','- Branch: `module-10-source-first-dry-run`','- Approved write scope: `Module10_Dry_Run`','- App root: `Module10_Dry_Run/standalone-course-mvp`','- Output root: `Module10_Dry_Run/_module10_dryrun_outputs`','','## Files Created','','' ]
fh += [f'- `{f}`' for f in files_created]
fh += ['','## Files Modified',''] + [f'- `{f}`' for f in files_modified]
fh += ['','## Proof Modifications Stayed Inside Module10_Dry_Run','','Generated/written paths are all prefixed with `Module10_Dry_Run/`. Outside dirty state sample remains unrelated/pre-existing:','','```text',outside,'```','', '## Source Coverage Result','',f'- Objectives covered: {len(objs)}/16','- Required source assets mapped: 17 including answer key internal-only.','- Source map files written: JSON and Markdown.','','## Weighted Time-Allotment Result','',f'- Weighted theory total: {sum(o["weighted_minutes"] for o in objs)} minutes.','- Assessment, clinical, certificate, and optional support time excluded.','','## LessonPlayer Decision','','Preserve/reuse existing `LessonPlayerPage.tsx` MediaLessonPlayer-equivalent and feed Module 10 source-first generated data. No blind replacement.','','## Images / Speech / SFX','','- Images: queued prompt-only, no image files generated.','- Speech audio: scripts and manifest generated; no final audio generated. Qwen/CI-ION reference recorded and generation remains gated.','- SFX: manifest generated with all required items queued/license-gated; no SFX used.','','## Build Result','','`npm install` completed with audit warnings; `npm run build` passed.','','## Validation Result','',f'Validation report result: **{validation_status}**. See `validation_report.md`.','','## Compliance Flags','','No PHI, approval, certificate-production, online clinical-credit, or online competency claim is intentionally present. Manual skills are treated as theory preparation and deferred to in-person/evaluator-supported work.','','## Unresolved Dependencies','','- SME/compliance review needed before production.','- TTS generation needs explicit media approval after script review.','- Licensed SFX sources must be selected before use.','- Image generation/tooling must be approved before generating final images.','- npm audit vulnerabilities should be triaged separately before production.','','## Paused / Terminated / Reassigned Workers','','- Paused jobs: none.','- Terminated/reassigned: packaged orchestrator failed before work; source-extraction async runner failed/disappeared after partial layout artifact. Parent orchestrator completed/reassigned those tasks manually under the wrapper-timeout/escalation rule.','','## Next Recommended Step','','Review `source_objective_map.*`, generated data, and validation report. Then run SME/compliance review before authorizing any final media generation or production packaging.']
(reports/'final_handoff.md').write_text('\n'.join(fh)+'\n',encoding='utf-8')
print('validation',validation_status)
print('reports written')
